[project]
name = "matvaretabellen-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.3.0",
    "requests>=2.32.5",
    "ruff>=0.12.10",
]
